baseURL = "https://www.milaiai.com"
title = "MILAI AI"
author = "Yubao"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "Blonde"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
googleAnalytics = "UA-131527698-4"

# Disqus Comment System
disqusShortname = "milaiai"

publishDir = "public"

# post_asset_folder = true

[params]
# Base color of the website.
# https://tailwindcss.com/docs/background-color
base_color = "bg-gray-800"

#Site description
description = "AI, XR, SLAM"

# The number of articles to be displayed on a single page.
paginator_pages = "10"

# Enable this if you want the archive list to be in a drop-down format.
archive_dropdown = "true"

# Number of tags to be displayed.
tagsLimit = 20

# Dark mode by default : dark
# Light mode by default : light
darkmode = "light"

  [params.ad]
    # Google AdSense
    # ex. ca-pub-0000000000000000
    googleAdSense = ""

    # ex. 000000000
    adslot = ""

    # Placement of ads
    postTop = false
    postBottom = false

  [params.post]
    # Show thumbnails
    thumbnail = true

    # Disable the "NO IMAGE" image.
    # noimage = true

    # See the Tailwind CSS documentation to set it up.
    # Recommended settings are h-32 to h-48.
    # https://tailwindcss.com/docs/height
    thumbnail_height = "lg:h-44"

    # https://tailwindcss.com/docs/width
    thumbnail_width = "lg:w-auto"

    # Number of characters in description
    description = "130"

  [params.widgets]
    # Display widgets
    display = true

    # Order of widgets to display
    widgets = [ "tags", "category",  "archive", "recent", "search"]

# If you're using Yandex.Metrica, you can enable this feature.
#[params.analytics.yandexmetrica]
#    enabled = true
#    tagNumber = ''

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 3

  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 3

[taxonomies]
category = "categories"
tag = "tags"
archive = "archives"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.x]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.x]
    disableInlineCSS = true

[markup.goldmark.renderer]
  unsafe = true

